# The Docker image that will be used to build your app
image: ruby:2.7
# Functions that should be executed before the build script is run
before_script:
  - apt update
  - apt install -y nodejs npm
  - gem install bundler
  - bundle install
pages:
  script:
    - mkdir .public
    - bundle exec jekyll build
    - cp -r * .public
    - mv .public public
    - ls -R
  artifacts:
    paths:
      # The folder that contains the files to be exposed at the Page URL
      - public
  rules:
    # This ensures that only pushes to the default branch will trigger
    # a pages deploy
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
